<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="salsalabs5" name="com.vitalii.vitaliiFramework2.tests.LoginPageTestsWD" tests="2" failures="0" timestamp="22 Feb 2017 15:55:44 GMT" time="0.025" errors="2">
  <testcase name="doSuccessfulLoginTest" time="0.023" classname="com.vitalii.vitaliiFramework2.tests.LoginPageTestsWD">
    <error type="org.testng.SkipException" message="This test has been skipped">
      <![CDATA[org.testng.SkipException: This test has been skipped
	at com.vitalii.vitaliiFramework2.listeners.TestResultListener.onTestSkipped(TestResultListener.java:36)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1653)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1645)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:703)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:970)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1149)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:75)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:46)
]]>
    </error>
  </testcase> <!-- doSuccessfulLoginTest -->
  <testcase name="doSuccessfulLoginTestAndPublishSignupForm" time="0.002" classname="com.vitalii.vitaliiFramework2.tests.LoginPageTestsWD">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.vitalii.vitaliiFramework2.helpers.Configurations.getEnvironmentUrl(Configurations.java:37)
	at com.vitalii.vitaliiFramework2.pages.LoginPage.openLoginPage(LoginPage.java:14)
	at com.vitalii.vitaliiFramework2.pages.LoginPage.doSuccessfulLogin(LoginPage.java:26)
	at com.vitalii.vitaliiFramework2.tests.LoginPageTestsWD.doSuccessfulLoginTestAndPublishSignupForm(LoginPageTestsWD.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:75)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:46)
]]>
    </error>
  </testcase> <!-- doSuccessfulLoginTestAndPublishSignupForm -->
</testsuite> <!-- com.vitalii.vitaliiFramework2.tests.LoginPageTestsWD -->
